"""Analyze the frozen SpatialEdit-Bench data (camera subset) for claim verification.

This script only reads files from the frozen data location:
  F:\\dataset\\2604.04911v1

It performs:
  1. Data inventory: task-type distribution in the meta file, camera triplet counts.
  2. Camera command geometry: parse each camera task JSON (edit_ypd), check
     prompt<->JSON consistency, and summarize the commanded (yaw, pitch, distance)
     distributions.
  3. Image sanity: all src/gt/pred images readable and dimensionally consistent.
  4. Metric aggregation: recompute Framing Error (FE) and Viewpoint Error (VE)
     aggregates from the per-sample CSV files produced by the previous
     reproduction runs (frozen artifacts), using the same formulas as the
     reproduction pipeline.

No model inference is run here: this environment has no GPU, ultralytics, cv2,
or vggt. The per-sample FE/VE CSVs were generated by running the public
reproduction pipeline on the real frozen benchmark triplets.
"""
from __future__ import annotations

import json
import os
import re
import sys
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image

# ---------------------------------------------------------------- constants
ROOT = Path(r"F:\dataset\2604.04911v1")
META_PATH = ROOT / "data" / "official" / "spatialedit-bench" / "SpatialEdit_Bench_Meta_File.json"
CAM_RESULTS_ROOT = (
    ROOT / "data" / "official" / "spatialedit-bench"
    / "SpatialEdit_Results" / "spatialedit" / "fullset" / "camera" / "en"
)
RESULTS_ROOT = ROOT / "results"
FE_CSV = RESULTS_ROOT / "fe_yolo11n_full" / "camera_framing_error_per_sample.csv"
VE_CSV = RESULTS_ROOT / "camera_viewpoint_error_per_sample.csv"

OUT_DIR = Path(__file__).resolve().parent.parent / "results"
OUT_DIR.mkdir(parents=True, exist_ok=True)

PAPER_FE = 0.527          # paper Table 2, camera framing error
PAPER_VE = 0.243          # paper Table 2, camera viewpoint error
PAPER_CAM_OVERALL = 0.385  # paper Table 2, camera overall error

FE_ANGLE_MAX_DEG = 20.0    # normalization used by the reproduction pipeline


# ------------------------------------------------------------------ helpers
def load_meta() -> list[dict]:
    with open(META_PATH, encoding="utf-8") as f:
        return json.load(f)


def find_camera_triplets() -> list[dict]:
    """Return list of {scene, edit_id, base_path} with complete triplet files."""
    triplets: list[dict] = []
    for scene in sorted(os.listdir(CAM_RESULTS_ROOT)):
        sp = CAM_RESULTS_ROOT / scene
        if not sp.is_dir():
            continue
        for fname in sorted(os.listdir(sp)):
            if not fname.endswith(".json"):
                continue
            base = fname[: -len(".json")]
            needed = [
                sp / f"{base}.json",
                sp / f"{base}.png",
                sp / f"{base}_gt.png",
                sp / f"{base}_src.png",
                sp / f"{base}_prompt.txt",
            ]
            if all(p.exists() for p in needed):
                triplets.append({"scene": scene, "edit_id": base, "base_path": sp / base})
    return triplets


def read_ypd(json_path: Path) -> dict:
    payload = json.loads(json_path.read_text(encoding="utf-8"))
    return dict(payload.get("metadata", {}).get("edit_ypd", {}))


def check_prompt_json_consistency(base_path: Path, ypd: dict) -> dict:
    """Check that the prompt text agrees with the structured command (edit_ypd)."""
    prompt_path = base_path.with_name(base_path.name + "_prompt.txt")
    if not prompt_path.exists():
        return {"prompt_found": False}
    prompt = prompt_path.read_text(encoding="utf-8")
    checks = {
        "prompt_found": True,
        "yaw_match": re.search(r"Yaw\s*(-?[\d.]+)°", prompt) is not None,
        "pitch_match": re.search(r"Pitch\s*(-?[\d.]+)°", prompt) is not None,
        "zoom_match": re.search(r"zoom:\s*(unchanged|in|out)", prompt) is not None,
    }
    if checks["yaw_match"]:
        m = re.search(r"Yaw\s*(-?[\d.]+)°", prompt)
        checks["yaw_val"] = float(m.group(1))
        checks["yaw_consistent"] = abs(checks["yaw_val"] - float(ypd.get("yaw", 0.0))) < 1e-6
    if checks["pitch_match"]:
        m = re.search(r"Pitch\s*(-?[\d.]+)°", prompt)
        checks["pitch_val"] = float(m.group(1))
        checks["pitch_consistent"] = abs(checks["pitch_val"] - float(ypd.get("pitch", 0.0))) < 1e-6
    if checks["zoom_match"]:
        m = re.search(r"zoom:\s*(unchanged|in|out)", prompt)
        zoom_word = m.group(1)
        dd = float(ypd.get("distance", 0.0))
        if dd < 0:
            expected_zoom = "in"
        elif dd > 0:
            expected_zoom = "out"
        else:
            expected_zoom = "unchanged"
        checks["zoom_word"] = zoom_word
        checks["zoom_consistent"] = zoom_word == expected_zoom
    return checks


def summarize_framing_from_csv(df: pd.DataFrame) -> dict:
    """Recompute FE summary from the per-sample framing CSV (same formulas as
    spatialedit_repro.camera_eval.summarize_framing_results)."""
    if df.empty:
        return {"n_images": 0}
    angle_error = float(df["gt_ray_diff_deg"].fillna(20.0).mean())
    zoom_error = float(df["zoom_dir_err"].fillna(1.0).mean())
    angle_norm = max(0.0, min(1.0, angle_error / FE_ANGLE_MAX_DEG))
    zoom_norm = max(0.0, min(1.0, zoom_error))
    return {
        "n_images": int(len(df)),
        "angle_error_deg": angle_error,
        "zoom_error": zoom_error,
        "angle_norm": angle_norm,
        "zoom_norm": zoom_norm,
        "overall_FE_error": (angle_norm + zoom_norm) / 2.0,
        "paper_framing_error": PAPER_FE,
        "paper_gap": (angle_norm + zoom_norm) / 2.0 - PAPER_FE,
        "angle_success": int(df["gt_ray_diff_deg"].notna().sum()),
        "zoom_success": int(df["log_scale"].notna().sum()),
    }


def summarize_viewpoint_from_csv(df: pd.DataFrame) -> dict:
    if df.empty:
        return {"n_images": 0}
    ok = df[df["status"] == "ok"]
    return {
        "n_images": int(len(df)),
        "n_success": int(len(ok)),
        "gt_xyz_err": float(df["gt_xyz_err"].mean()),
        "gt_ypr_err": float(df["gt_ypr_err"].mean()),
        "overall_VE_error": float(df["overall_VE_error"].mean()),
        "paper_viewpoint_error": PAPER_VE,
        "paper_gap": float(df["overall_VE_error"].mean()) - PAPER_VE,
    }


# ------------------------------------------------------------------- main
def main() -> dict:
    report: dict = {}

    # 1. meta inventory
    meta = load_meta()
    types = Counter(d.get("type") for d in meta)
    report["meta"] = {
        "total_tasks": len(meta),
        "task_types": dict(types),
        "unique_image_ids": len({d["image_id"] for d in meta}),
        "camera_task_count": types.get("camera", 0),
        "move_task_count": types.get("move", 0),
        "rotate_task_count": types.get("rotate", 0),
    }

    # camera meta entries that are expected to exist as results
    camera_meta_ids = {d["edit_id"] for d in meta if d.get("type") == "camera"}
    report["meta"]["camera_meta_edit_ids"] = len(camera_meta_ids)

    # 2. camera triplets on disk
    triplets = find_camera_triplets()
    report["camera_triplets"] = {
        "n_complete_triplets_on_disk": len(triplets),
        "n_scene_dirs": len([d for d in os.listdir(CAM_RESULTS_ROOT) if (CAM_RESULTS_ROOT / d).is_dir()]),
        "n_triplets_with_meta_entry": sum(1 for t in triplets if t["edit_id"] in camera_meta_ids),
    }

    # 3. camera command geometry
    yaws, pitches, dds = [], [], []
    prompt_ok = 0
    prompt_total = 0
    command_value_counts = Counter()
    for t in triplets:
        ypd = read_ypd(t["base_path"].with_suffix(".json"))
        yaws.append(float(ypd.get("yaw", 0.0)))
        pitches.append(float(ypd.get("pitch", 0.0)))
        dds.append(float(ypd.get("distance", 0.0)))
        command_value_counts[(round(float(ypd.get("yaw", 0.0))), round(float(ypd.get("pitch", 0.0))))] += 1
        chk = check_prompt_json_consistency(t["base_path"], ypd)
        if chk.get("prompt_found"):
            prompt_total += 1
            if all(
                chk.get(k, True)
                for k in ("yaw_consistent", "pitch_consistent", "zoom_consistent")
            ):
                prompt_ok += 1
    yaws_a = np.asarray(yaws)
    pitches_a = np.asarray(pitches)
    dds_a = np.asarray(dds)

    # check quantization: yaw multiples of 45, pitch multiples of 15
    yaw_rem = np.abs(yaws_a % 45.0)
    yaw_rem = np.minimum(yaw_rem, 45.0 - yaw_rem)
    pitch_rem = np.abs(pitches_a % 15.0)
    pitch_rem = np.minimum(pitch_rem, 15.0 - pitch_rem)

    report["camera_commands"] = {
        "n_triplets_with_commands": len(triplets),
        "yaw_min": float(yaws_a.min()),
        "yaw_max": float(yaws_a.max()),
        "pitch_min": float(pitches_a.min()),
        "pitch_max": float(pitches_a.max()),
        "distance_min": float(dds_a.min()),
        "distance_max": float(dds_a.max()),
        "n_zoom_in": int((dds_a < 0).sum()),
        "n_zoom_out": int((dds_a > 0).sum()),
        "n_no_zoom": int((dds_a == 0).sum()),
        "yaw_multiples_of_45_frac": float((yaw_rem < 1e-6).mean()),
        "pitch_multiples_of_15_frac": float((pitch_rem < 1e-6).mean()),
        "prompt_json_consistent_frac": (prompt_ok / prompt_total) if prompt_total else None,
        "unique_yaw_values": sorted({round(v) for v in yaws_a.tolist()}),
        "unique_pitch_values": sorted({round(v) for v in pitches_a.tolist()}),
        "yaw_pitch_command_counts": {f"y={k[0]},p={k[1]}": v for k, v in sorted(command_value_counts.items())},
    }

    # 4. image sanity
    img_ok = 0
    img_total = 0
    sizes = Counter()
    for t in triplets:
        for suffix in ("_src.png", "_gt.png", ".png"):
            p = t["base_path"].with_name(t["base_path"].name + suffix)
            try:
                with Image.open(p) as im:
                    im.verify()
                with Image.open(p) as im:
                    sizes[im.size] += 1
                img_ok += 1
            except Exception:
                pass
            img_total += 1
    report["image_sanity"] = {
        "readable_fraction": img_ok / img_total if img_total else None,
        "size_counter": {f"{w}x{h}": c for (w, h), c in sizes.items()},
    }

    # 5. FE / VE aggregation from frozen per-sample CSVs
    fe_summary = {}
    if FE_CSV.exists():
        df = pd.read_csv(FE_CSV)
        fe_summary = summarize_framing_from_csv(df)
    ve_summary = {}
    if VE_CSV.exists():
        df = pd.read_csv(VE_CSV)
        ve_summary = summarize_viewpoint_from_csv(df)

    report["framing_error_repro"] = fe_summary
    report["viewpoint_error_repro"] = ve_summary
    if fe_summary.get("overall_FE_error") is not None and ve_summary.get("overall_VE_error") is not None:
        report["camera_overall_repro"] = {
            "camera_overall_error": (fe_summary["overall_FE_error"] + ve_summary["overall_VE_error"]) / 2.0,
            "paper_camera_overall_error": PAPER_CAM_OVERALL,
        }

    return report


if __name__ == "__main__":
    report = main()
    out = OUT_DIR / "frozen_data_analysis.json"
    out.write_text(json.dumps(report, indent=2, ensure_ascii=False))
    print(json.dumps(report, indent=2, ensure_ascii=False))
    print(f"\nWrote {out}")
